In [2]:
import pandas as pd
import numpy as np
import re
import nltk
import spacy
import string
pd.options.mode.chained_assignment = None

In [3]:
full_df = pd.read_csv("twcs.csv")
full_df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [6]:
df=full_df[['text']]

In [7]:
df.head()

                                                text
0  @115712 I understand. I would like to assist y...
1      @sprintcare and how do you propose we do that
2  @sprintcare I have sent several private messag...
3  @115712 Please send us a Private Message so th...
4                                 @sprintcare I did.

In [8]:
df['text']=df['text'].astype(str)
df.head()

                                                text
0  @115712 I understand. I would like to assist y...
1      @sprintcare and how do you propose we do that
2  @sprintcare I have sent several private messag...
3  @115712 Please send us a Private Message so th...
4                                 @sprintcare I did.

In [24]:
df['text_lower']=df['text'].str.lower()
df.head()

,text,text_to_punct,text_to_stop,text_lower
0,@115712 I understand. I would like to assist y...,115712 I understand I would like to assist you...,115712 I understand I would like assist We wou...,@115712 i understand. i would like to assist y...
1,@sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcare propose,@sprintcare and how do you propose we do that
2,@sprintcare I have sent several private messag...,sprintcare I have sent several private message...,sprintcare I sent several private messages one...,@sprintcare i have sent several private messag...
3,@115712 Please send us a Private Message so th...,115712 Please send us a Private Message so tha...,115712 Please send us Private Message assist J...,@115712 please send us a private message so th...
4,@sprintcare I did.,sprintcare I did,sprintcare I,@sprintcare i did.

In [23]:
#drop last created column
df.drop(['text_lower'], axis = 1, inplace = True)

In [11]:
df.head()

                                                text
0  @115712 I understand. I would like to assist y...
1      @sprintcare and how do you propose we do that
2  @sprintcare I have sent several private messag...
3  @115712 Please send us a Private Message so th...
4                                 @sprintcare I did.

In [25]:
#remove punctuatuion 
punct_to_remove = string.punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans(" "," ", punct_to_remove))
df['text_to_punct']=df['text_lower'].apply(lambda text:remove_punctuation(text))
df.head()

,text,text_to_punct,text_to_stop,text_lower
0,@115712 I understand. I would like to assist y...,115712 i understand i would like to assist you...,115712 I understand I would like assist We wou...,@115712 i understand. i would like to assist y...
1,@sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcare propose,@sprintcare and how do you propose we do that
2,@sprintcare I have sent several private messag...,sprintcare i have sent several private message...,sprintcare I sent several private messages one...,@sprintcare i have sent several private messag...
3,@115712 Please send us a Private Message so th...,115712 please send us a private message so tha...,115712 Please send us Private Message assist J...,@115712 please send us a private message so th...
4,@sprintcare I did.,sprintcare i did,sprintcare I,@sprintcare i did.

In [14]:
from nltk.corpus import stopwords
", ".join(stopwords.words('english'))

"i, me, my, myself, we, our, ours, ourselves, you, you're, you've, you'll, you'd, your, yours, yourself, yourselves, he, him, his, himself, she, she's, her, hers, herself, it, it's, its, itself, they, them, their, theirs, themselves, what, which, who, whom, this, that, that'll, these, those, am, is, are, was, were, be, been, being, have, has, had, having, do, does, did, doing, a, an, the, and, but, if, or, because, as, until, while, of, at, by, for, with, about, against, between, into, through, during, before, after, above, below, to, from, up, down, in, out, on, off, over, under, again, further, then, once, here, there, when, where, why, how, all, any, both, each, few, more, most, other, some, such, no, nor, not, only, own, same, so, than, too, very, s, t, can, will, just, don, don't, should, should've, now, d, ll, m, o, re, ve, y, ain, aren, aren't, couldn, couldn't, didn, didn't, doesn, doesn't, hadn, hadn't, hasn, hasn't, haven, haven't, isn, isn't, ma, mightn, mightn't, mustn, mustn't, needn, needn't, shan, shan't, shouldn, shouldn't, wasn, wasn't, weren, weren't, won, won't, wouldn, wouldn't"

In [26]:
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])
df['text_to_stop']=df['text_to_punct'].apply(lambda text: remove_stopwords(text))
df.head()

,text,text_to_punct,text_to_stop,text_lower
0,@115712 I understand. I would like to assist y...,115712 i understand i would like to assist you...,115712 understand would like assist would need...,@115712 i understand. i would like to assist y...
1,@sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcare propose,@sprintcare and how do you propose we do that
2,@sprintcare I have sent several private messag...,sprintcare i have sent several private message...,sprintcare sent several private messages one r...,@sprintcare i have sent several private messag...
3,@115712 Please send us a Private Message so th...,115712 please send us a private message so tha...,115712 please send us private message assist c...,@115712 please send us a private message so th...
4,@sprintcare I did.,sprintcare i did,sprintcare,@sprintcare i did.

In [32]:
from collections import Counter 
cnt = Counter()
for text in df['text_to_stop'].values:
    for word in text.split():
        cnt[word]+=1
        
    
cnt.most_common(10)

[('us', 451262),
 ('please', 402709),
 ('dm', 335374),
 ('help', 267633),
 ('hi', 224603),
 ('thanks', 206452),
 ('get', 200374),
 ('sorry', 192246),
 ('like', 146385),
 ('know', 145407)]

In [37]:
FREQWORDS = [w for (w, wc) in cnt.most_common(10)]
def remove_freqwords(text):
    return " ".join([word for word in str(text).split() if word not in FREQWORDS])
df['text_to_freqwords'] = df['text_to_stop'].apply(lambda text: remove_freqwords(text))
df.head()

,text,text_to_punct,text_to_stop,text_lower,text_to_freqwords
0,@115712 I understand. I would like to assist y...,115712 i understand i would like to assist you...,115712 understand would like assist would need...,@115712 i understand. i would like to assist y...,115712 understand would assist would need priv...
1,@sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcare propose,@sprintcare and how do you propose we do that,sprintcare propose
2,@sprintcare I have sent several private messag...,sprintcare i have sent several private message...,sprintcare sent several private messages one r...,@sprintcare i have sent several private messag...,sprintcare sent several private messages one r...
3,@115712 Please send us a Private Message so th...,115712 please send us a private message so tha...,115712 please send us private message assist c...,@115712 please send us a private message so th...,115712 send private message assist click ‘mess...
4,@sprintcare I did.,sprintcare i did,sprintcare,@sprintcare i did.,sprintcare

In [38]:
FREQWORDS

['us', 'please', 'dm', 'help', 'hi', 'thanks', 'get', 'sorry', 'like', 'know']

In [42]:
df.drop(['text_to_punct','text_to_stop','text_lower'],axis=1,inplace=True)

In [43]:
df.head()

,text,text_to_freqwords
0,@115712 I understand. I would like to assist y...,115712 understand would assist would need priv...
1,@sprintcare and how do you propose we do that,sprintcare propose
2,@sprintcare I have sent several private messag...,sprintcare sent several private messages one r...
3,@115712 Please send us a Private Message so th...,115712 send private message assist click ‘mess...
4,@sprintcare I did.,sprintcare

In [44]:
#remove rare words
rare_word = 10
RARE_WORDS = [w for (w, wc) in cnt.most_common()[:-rare_word-1:-1]]
def remove_rarewords(text):
    return " ".join([word for word in str(text).split() if word not in RAREWORDS])
df['text_to_rareword']= df['text_to_freqwords'].apply(lambda text: remove_freqwords(text))
df.head()

,text,text_to_freqwords,text_to_rareword
0,@115712 I understand. I would like to assist y...,115712 understand would assist would need priv...,115712 understand would assist would need priv...
1,@sprintcare and how do you propose we do that,sprintcare propose,sprintcare propose
2,@sprintcare I have sent several private messag...,sprintcare sent several private messages one r...,sprintcare sent several private messages one r...
3,@115712 Please send us a Private Message so th...,115712 send private message assist click ‘mess...,115712 send private message assist click ‘mess...
4,@sprintcare I did.,sprintcare,sprintcare

In [45]:
RARE_WORDS

['notjustxmasallyearround',
 'httpstco7uqpwyh1b6',
 '823870',
 'httpstcogfyuq1kjtk',
 'httpstcov2tmhetl7q',
 '823869',
 'httpstco4v1ft0th5x',
 '823868',
 '823867',
 'httpstco4dhaxwnqb4']

In [46]:
#stemming
from nltk.stem.porter import PorterStemmer

In [48]:
df.drop(['text_to_freqwords','text_to_rareword'],axis = 1, inplace = True)

In [49]:
stemmer = PorterStemmer()
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])
df["text_stemmed"] = df['text'].apply(lambda text: stem_words(text))

In [50]:
df.head()

,text,text_stemmed
0,@115712 I understand. I would like to assist y...,@115712 i understand. i would like to assist y...
1,@sprintcare and how do you propose we do that,@sprintcar and how do you propos we do that
2,@sprintcare I have sent several private messag...,@sprintcar i have sent sever privat messag and...
3,@115712 Please send us a Private Message so th...,@115712 pleas send us a privat messag so that ...
4,@sprintcare I did.,@sprintcar i did.

In [51]:
#lemmetization
from nltk.stem import WordNetLemmatizer
lemmetizer = WordNetLemmatizer()
def lemmetize_word(text):
    return " ".join([lemmetizer.lemmatize(word) for word in text.split()])
df['lemmetized_word'] = df['text'].apply(lambda text: lemmetize_word(text))
df.head()

,text,text_stemmed,lemmetized_word
0,@115712 I understand. I would like to assist y...,@115712 i understand. i would like to assist y...,@115712 I understand. I would like to assist y...
1,@sprintcare and how do you propose we do that,@sprintcar and how do you propos we do that,@sprintcare and how do you propose we do that
2,@sprintcare I have sent several private messag...,@sprintcar i have sent sever privat messag and...,@sprintcare I have sent several private messag...
3,@115712 Please send us a Private Message so th...,@115712 pleas send us a privat messag so that ...,@115712 Please send u a Private Message so tha...
4,@sprintcare I did.,@sprintcar i did.,@sprintcare I did.

In [54]:
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer

In [58]:
#remove urls
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'',text)

In [59]:
#Remove html tages
def remove_htlm(text):
    html_patternv = re.compile('<.*?>')
    return html_pattern.sub(r'',text)

In [ ]:
lemmetizer = WordNetLemmatizer()
wordnet_map = {"N":wordnet.NOUN, "V":wordnet.VERB, "J":wordnet.ADJ, "R":wordnet.ADV}
def lemmetize_words(text):
    pos_tagged_text = nltk.pos_tag(text.split())
    return " ".join([lemmetizer.lemmatize(word, wordnet_map.get(pos[0],wordnet.NOUN)) for word, pos in pos_tagged_text])
df['text_lemmetized']= df['text'].apply(lambda text: lemmetize_words(text))
df.head()